export type Priority = 'alta' | 'media' | 'baja';
export type Status = 'pendiente' | 'en_progreso' | 'terminada';
export type Role = 'admin' | 'colaborador';
export type ProductStatus = 'activo' | 'pausado' | 'agotado';
export type SellerStatus = 'activo' | 'inactivo';
export type PaymentStatus = 'pendiente' | 'pagado';

// Creative types
export type CreativeType = 'imagen' | 'video' | 'copy';
export type CreativeChannel = 'whatsapp' | 'instagram' | 'tiktok' | 'facebook' | 'web';
export type CreativeObjective = 'vender' | 'atraer' | 'probar';
export type CreativeStatus = 'pendiente' | 'generando' | 'generado' | 'publicado' | 'descartado';
export type CreativeResult = 'sin_evaluar' | 'funciono' | 'no_funciono';

export interface Project {
  id: string;
  name: string;
  description: string;
  dueDate: string;
  createdAt: string;
}

export interface Task {
  id: string;
  projectId: string;
  name: string;
  description: string;
  status: Status;
  priority: Priority;
  dueDate: string;
  createdAt: string;
  assignedTo?: string;
  assignedUser?: Profile;
}

export interface Profile {
  id: string;
  fullName: string;
  email: string;
  avatarUrl?: string;
  createdAt: string;
}

export interface UserRole {
  id: string;
  userId: string;
  role: Role;
}

// Extended Product for GRC
export interface Product {
  id: string;
  name: string;
  price: number;
  storeName?: string;
  imageUrl?: string;
  description?: string;
  createdAt: string;
  updatedAt: string;
  // GRC fields
  supplierId?: string;
  supplier?: Supplier;
  supplierPrice: number;
  suggestedPrice: number;
  status: ProductStatus;
  isFeatured: boolean;
  category?: string;
  internalNotes?: string;
  sku?: string;
}

export interface Supplier {
  id: string;
  name: string;
  contact?: string;
  conditions?: string;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Seller {
  id: string;
  name: string;
  contact?: string;
  commission: number;
  status: SellerStatus;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Sale {
  id: string;
  productId?: string;
  product?: Product;
  sellerId?: string;
  seller?: Seller;
  clientName?: string;
  quantity: number;
  unitPrice: number;
  totalAmount: number;
  paymentMethod?: string;
  paymentStatus: PaymentStatus;
  saleDate: string;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

// Creative Intelligence
export interface Creative {
  id: string;
  productId?: string;
  product?: Product;
  type: CreativeType;
  channel: CreativeChannel;
  objective: CreativeObjective;
  status: CreativeStatus;
  result: CreativeResult;
  title?: string;
  copy?: string;
  imageUrl?: string;
  videoUrl?: string;
  script?: string;
  learning?: string;
  aiPrompt?: string;
  publishedAt?: string;
  createdAt: string;
  updatedAt: string;
}

// Smart Task (generated by system logic)
export interface SmartTask {
  id: string;
  type: 'cobro' | 'creativo' | 'promocion' | 'actualizacion' | 'seguimiento';
  title: string;
  description: string;
  impact: 'ventas' | 'cobro' | 'crecimiento';
  priority: Priority;
  relatedSaleId?: string;
  relatedProductId?: string;
  relatedCreativeId?: string;
  actionLabel: string;
  actionPath?: string;
}

// Dashboard KPIs
export interface DashboardStats {
  totalSales: number;
  totalRevenue: number;
  pendingPayments: number;
  pendingAmount: number;
  activeProducts: number;
  pendingCreatives: number;
  publishedCreatives: number;
}

// Business Summary
export interface BusinessSummary {
  salesThisMonth: number;
  revenueThisMonth: number;
  pendingCollections: number;
  pendingCollectionAmount: number;
  activeProducts: number;
  featuredProducts: number;
  creativesTotal: number;
  creativesPending: number;
  creativesPublished: number;
}
